import type { Metadata } from 'next';
import type { ReactNode } from 'react';
import { Geist, Geist_Mono, JetBrains_Mono } from 'next/font/google';
import '@/globals.css';
import { cn } from '@shared/lib/utils';
import { SvgSprite } from '@widgets/svg-sprite';
import { getStaticParams } from '@shared/lib/i18n';
import { RootLayoutHeader } from './RootLayoutHeader';

const jetbrainsMono = JetBrains_Mono({ subsets: ['latin'], variable: '--font-mono' });

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type RootLayoutProps = {
  children: ReactNode;
};

export function generateStaticParams() {
  return getStaticParams();
}

export const RootLayout = async (props: RootLayoutProps) => {
  const { children } = props;

  return (
    <html
      className={cn(
        'h-full',
        'antialiased',
        geistSans.variable,
        geistMono.variable,
        'font-mono',
        jetbrainsMono.variable,
      )}
    >
      <body className="flex min-h-full flex-col">
        <RootLayoutHeader />
        <main className="flex min-h-screen flex-1 flex-col items-center bg-black p-10 pt-[calc(var(--root-header-height)+(var(--spacing)*4))] font-sans">
          {children}
        </main>
        <SvgSprite />
      </body>
    </html>
  );
};
